name: SCP Policy Fetch

on:
  pull_request:

jobs:
  fetch_scp:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: install psynth cli
      run: |
        pip install -e .
        pip show psynth
    
    - name: configure credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_LINGFEI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_LINGFEI }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: fetch policies
      run: |
        psynth fetch-scp
      env:
        OUTPUT_FILE: service_control_policies.json
    
    - name: upload policies to github
      uses: actions/upload-artifact@v4
      with:
        name: service_control_policies
        path: service_control_policies.json
        retention-days: 7
